"""Adding column purchase_date.

Revision ID: 17df9cfba6a5
Revises: 889a44915712
Create Date: 2021-11-19 14:42:35.601664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17df9cfba6a5'
down_revision = '889a44915712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'stocks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'purchase_date')
    # ### end Alembic commands ###
